// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NudgeApp.Data;

namespace NudgeApp.Data.Migrations
{
    [DbContext(typeof(NudgeDbContext))]
    partial class NudgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NudgeApp.Data.Entities.AnonymousNudgeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActualTransportationType");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("PrecipitationProbability");

                    b.Property<int>("Result");

                    b.Property<int>("RoadCondition");

                    b.Property<int>("SkyCoverage");

                    b.Property<float>("Temperature");

                    b.Property<int>("UserPreferedTransportationType");

                    b.Property<float>("Wind");

                    b.HasKey("Id");

                    b.ToTable("AnonymousNudges");
                });

            modelBuilder.Entity("NudgeApp.Data.Entities.NudgeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("NudgeResult");

                    b.Property<int>("TransportationType");

                    b.Property<Guid>("TripId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Nudges");
                });

            modelBuilder.Entity("NudgeApp.Data.Entities.PreferencesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ActualTransportationType");

                    b.Property<int>("AimedTransportationType");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("PreferedTransportationType");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("NudgeApp.Data.Entities.PushNotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Auth");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Endpoint");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("P256DH");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("PushNotifications");
                });

            modelBuilder.Entity("NudgeApp.Data.Entities.TripEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("DistanceTraveled");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("Type");

                    b.Property<int>("UsedTransportationType");

                    b.Property<Guid>("WeatherForecastId");

                    b.HasKey("Id");

                    b.HasIndex("WeatherForecastId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("NudgeApp.Data.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Email");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NudgeApp.Data.Entities.WeatherForecastEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CloudCoveragePercent");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<int>("PrecipitationProbability");

                    b.Property<float>("ReafFeelTemperature");

                    b.Property<int>("RoadCondition");

                    b.Property<float>("Temperature");

                    b.Property<DateTime>("Time");

                    b.Property<float>("Wind");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecast");
                });

            modelBuilder.Entity("NudgeApp.Data.Entities.NudgeEntity", b =>
                {
                    b.HasOne("NudgeApp.Data.Entities.TripEntity", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NudgeApp.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NudgeApp.Data.Entities.PreferencesEntity", b =>
                {
                    b.HasOne("NudgeApp.Data.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NudgeApp.Data.Entities.TripEntity", b =>
                {
                    b.HasOne("NudgeApp.Data.Entities.WeatherForecastEntity", "WeatherForecast")
                        .WithMany()
                        .HasForeignKey("WeatherForecastId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
